### ISSUE TITLE
问下，如何计算left,right,top,bottom

### ISSUE THREAD

**Issue by yiwei19850813** [Sinkup/CameraStickerDemo#2]
没有看明白，旋转的时候vertices[] 的这8个点如何确定的，求解答

**Comment by rogerou** [comment]
@yiwei19850813 我也没看懂

**Comment by rogerou** [comment]
@Sinkup 看起来是像绕Z轴旋转 只是旋转理应只是那个Top left right bottom 旋转，但是它这里减去中点的值旋转完再加回去 感觉不太能理解，是让旋转的角度变小吗还是怎样？

**Comment by Sinkup** [comment]
@rogerou 如果不减去中心点，就是绕原点 (0, 0) 来旋转的
